#!/usr/bin/perl -w

use strict;
use warnings;

print <<HTML
<!DOCTYPE html>
<html>

	<head>
		<title>Perl Extensionless Script</title>
		<meta name='viewport' content='width=device-width, initial-scale=1'>
		<meta charset='utf-8'>
		<link rel='stylesheet' type='text/css' href='http://perl-executing-browser-pseudodomain/bootstrap/css/themes/darkly-theme.css' media='all'/>
	</head>

	<body>
		<p><font size='5'>Perl Extensionless Script</font></p>
		<p><font size='3'>Hello from a Perl script without file extension!</font></p>
	</body>

</html>
HTML
;
