#!/usr/bin/env python

print "Content-type: text/html\r\n\r\n";

print "<html>";

print "<head>";
print "<title>Python Extensionless Script</title>";
print "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\n";
print "</head>\n";

print "<body>";
print "<p align='center'><font size='5' face='SansSerif'>Python Extensionless Script</font></p>";
print "<p align='center'><font size='3' face='SansSerif'>Hello from a Python script without extension!</font></p>";
print "</body>";

print "</html>";
