/*
 * Dark theme for Perl Executing Browser
 * By Valcho Nedelchev
 */
*{
	font-family: sans-serif;
	color: #000000;
}
body {
	background-color: #ffffb8;
}
input[type=submit],
input[type=reset],
button
{
	color: #333;
	background-color: #ccc;
	font-size:0.875em;
}
a {
	color: #a03830;
	text-decoration: none;
}
.center { 
	text-align: center; 
}
footer {
	padding: 1em;
	font-size:0.875em;
	text-align: center;
}
