#!/usr/bin/perl -w

# Copyright (c) 2005 Hans Jeuken. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.

use strict;
use Term::ANSIColor;
use Syntax::Highlight::Engine::Kate;

# Define variables:
my $input_filename = $ARGV[0]; # input file is the first and only needed command line argument
my $input_filehandle;
my $first_line;
my $language;
my $line_number;

# Remove double slash '//' from script filenames:
$input_filename =~ s/\/\//\//g;

# Detect script language by file extension:
if ($input_filename =~ ".pl" or $input_filename =~ ".PL"){
	$language = "Perl";
}
if ($input_filename =~ ".py" or $input_filename =~ ".PY"){
	$language = "Python";
}
if ($input_filename =~ ".php" or $input_filename =~ ".PHP"){
	$language = "PHP (HTML)";
}

# Detect script language by shebang line:
# Open the input file read-only to detect the shebang line:
open ($input_filehandle, "<", "$input_filename");

# Detect Perl and Python using the shebang line.
# Perl and Python scripts may not have a file extension.
$first_line = <$input_filehandle>;
if ($first_line =~ m/\#\!.*perl/){
	$language = "Perl";
}
if ($first_line =~ m/\#\!.*python/){
	$language = "Python";
}

# Close the input file:
close ($input_filehandle);

# Syntax::Highlight::Engine::Kate settings:
 my $hl = new Syntax::Highlight::Engine::Kate(
    language => $language,
    substitutions => {
       "<" => "&lt;",
       ">" => "&gt;",
       "&" => "&amp;",
       " " => "&nbsp;",
       "\t" => "&nbsp;&nbsp;&nbsp;",
       "\n" => "<BR>\n",
    },
    format_table => {
       Alert => ["<font color=\"#0000ff\">", "</font>"],
       BaseN => ["<font color=\"#007f00\">", "</font>"],
       BString => ["<font color=\"#c9a7ff\">", "</font>"],
       Char => ["<font color=\"#ff00ff\">", "</font>"],
       Comment => ["<font color=\"#7f7f7f\"><i>", "</i></font>"],
       DataType => ["<font color=\"#0000ff\">", "</font>"],
       DecVal => ["<font color=\"#00007f\">", "</font>"],
       Error => ["<font color=\"#ff0000\"><b><i>", "</i></b></font>"],
       Float => ["<font color=\"#00007f\">", "</font>"],
       Function => ["<font color=\"#007f00\">", "</font>"],
       IString => ["<font color=\"#ff0000\">", ""],
       Keyword => ["<b>", "</b>"],
       Normal => ["", ""],
       Operator => ["<font color=\"#ffa500\">", "</font>"],
       Others => ["<font color=\"#b03060\">", "</font>"],
       RegionMarker => ["<font color=\"#96b9ff\"><i>", "</i></font>"],
       Reserved => ["<font color=\"#9b30ff\"><b>", "</b></font>"],
       String => ["<font color=\"#ff0000\">", "</font>"],
       Variable => ["<font color=\"#0000ff\"><b>", "</b></font>"],
       Warning => ["<font color=\"#0000ff\"><b><i>", "</b></i></font>"],
    },
 );

# Open the input file read-only to highlight the syntax:
open ($input_filehandle, "<", "$input_filename");

# Highlight the syntax of the input file:
print "<html>\n";
print "<head>\n";
#print "<title>Syntax::Highlight::Engine::Kate Source Viewer</title>\n";
print "<title>$input_filename</title>\n";
print "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\n";
print "</head>\n";
while (my $in = <$input_filehandle>) {
	$line_number++;
	print "<a name='line$line_number' href='#line$line_number'>$line_number</a> &nbsp;";
	print $hl->highlightText($in);
}
print "</body>\n</html>\n";

# Close the input file:
close ($input_filehandle);
