#!/usr/bin/perl -w

# UTF-8 encoded file

use strict;
use warnings;

print <<HTML
<!DOCTYPE html>
<html>

	<head>
		<title>Perl Extensionless Script</title>
		<meta name='viewport' content='width=device-width, initial-scale=1'>
		<meta charset='utf-8'>
	</head>

	<body>
		<p align='center'><font size='5'>Perl Extensionless Script</font></p>
		<p align='center'><font size='3'>Hello from a Perl script without extension!</font></p>
	</body>

</html>
HTML
;
